### PR TITLE
Add SIRIS

### PR DESCRIPTION
**Pull request by Dexus**

### CODE REVIEW

**Comment by smallnest** [comment]
don't change README and imports. We can't check diff after your committed.  Only add your method and import

**Comment by Dexus** [comment]
Sorry GO sorts automatical done with my IDE... and the sorts for the README because of your info in the readme... but i will rebase it in 30 minutes...

**Comment by smallnest** [comment]
I have added SIRIS. Thanks

**Comment by Dexus** [comment]
Thank you @smallnest

**Pull request closed without merging**
